export const GUEST = {
  ADD: 'ADD_GUEST',
  DELETE: 'DELETE_GUEST',
  GET: 'GET_INFO_GUEST',
  ATTENDING: 'GUEST_ATTENDING',
  UNDEFINED: 'UNDEFINED_GUEST',
  LIST: 'LIST_GUEST',
  LIST_ALL: 'ALL_GUEST_OF_THIS_ACCOUNT',
  SET_STATUS: 'SET_STATUS_GUEST',
  CHECKIN: "GUEST_CHECK_IN"
};

export const TITLE = {
  WELCOME: 'WELCOME_TITLE',
  LIVEVIEW: 'LIVEVIEW_TITLE',
};

export const MEETING = {
  LIST: "LIST_MEETING",
  GET: 'GET_INFO_MEETING',
  DELETE: 'DELETE_MEETING',
  CREATE: "CREATE_MEETING",
  START: "START_MEETING",
  CODE: "CODE_MEETING",
  JOIN: "JOIN_MEETING",
  END: "END_MEETING",
  SET_STATUS: "SET_STATUS_MEETING",
  TITLE: "TITLE_MEETING"
}

export const STATUS = {
  SUCCESS: "SUCCESS",
  FAIL: "FAIL"
}
export const ERROR = {
  NOT_EXIST: "NOT_EXIST"
}

export const ACCOUNT = {
  ATTENDING: 'THIS_ACCOUNT',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  VERIFY: 'VERIFY'
};
